feat: Dock 追加失敗時に警告を出力

diff --git a/home/.chezmoiscripts/run_after_once_20-darwin-setup-dock.sh.tmpl b/home/.chezmoiscripts/run_after_once_20-darwin-setup-dock.sh.tmpl
--- a/home/.chezmoiscripts/run_after_once_20-darwin-setup-dock.sh.tmpl
+++ b/home/.chezmoiscripts/run_after_once_20-darwin-setup-dock.sh.tmpl
@@ -14,6 +14,7 @@ defaults write com.apple.dock persistent-apps -array
 # アプリを追加する関数（存在するアプリのみ追加）
 add_app() {
   if [ ! -e "$1" ]; then
+    echo "[Warn]: Failed to add to the Dock. This app was not found. : $1" >&2
     return
   fi
   defaults write com.apple.dock persistent-apps -array-add \
